# Generated by Django 5.0.7 on 2024-07-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('level', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'reserve',
                'ordering': ['date', 'time'],
            },
        ),
    ]
